name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set short commit SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/stig-bee:${{ env.SHORT_SHA }} \
            --tag ghcr.io/${{ github.repository_owner }}/stig-bee:latest \
            
      - name: Push the Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/stig-bee:${{ env.SHORT_SHA }}
          docker push ghcr.io/${{ github.repository_owner }}/stig-bee:latest
      - name: Build the Docker_ecs image
        run: |
          docker build . --file Dockerfile_ecs \
            --tag ghcr.io/${{ github.repository_owner }}/stig-bee:${{ env.SHORT_SHA }}-ecs \
            --tag ghcr.io/${{ github.repository_owner }}/stig-bee:latest-ecs \
      - name: Push the Docker_ecs image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/stig-bee:${{ env.SHORT_SHA }}-ecs
          docker push ghcr.io/${{ github.repository_owner }}/stig-bee:latest-ecs